service: users-api-rest
frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs14.x
    environment:
        DYNAMODB_TABLE: users
        TWITTER_API_KEY: twitter_api_key
        TWITTER_API_SECRET_KEY: twitter_api_secret_key
    lambdaHashingVersion: 20201221
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                      - dynamodb:DeleteItem
                  Resource: 'arn:aws:dynamodb:us-east-1:275665998423:table/users'

plugins:
    - serverless-offline

cors:
    - enabled: true
    - origin: '*'
    - headers: 'Content-Type, Authorization,Accept,Origin'
    - methods: 'GET,PUT,POST,DELETE'

functions:
    findOne:
        handler: handler.findOne
        events:
            - http:
                  path: users/{id}
                  method: get
    update:
        handler: handler.update
        events:
            - http:
                  path: users/{id}
                  method: put
    tweets:
        handler: handler.tweets
        events:
            - http:
                  path: users/{username}/tweets
                  method: get
custom:
    serverless-offline:
        httpPort: 3001
