service: aws-node-twitter-integration
frameworkVersion: '2'

provider:
    name: aws
    runtime: nodejs14.x
    lambdaHashingVersion: 20201221

functions:
    tweets:
        handler: handler.tweets
        events:
            - http:
                  path: users/{username}/tweets
                  method: get
